services:
  microserviceapi.orders:
    container_name: orders-api
    image: testmicroservicesregistrydocker.azurecr.io/microservice-orders:latest
    build:
      context: .
      dockerfile: MicroserviceAPI.Orders/Dockerfile
    ports: 
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${ORDERS_DB_CONNECTION_STRING}
    depends_on:
      - microserviceapi.payments

  microserviceapi.payments:
    container_name: payments-api
    image: testmicroservicesregistrydocker.azurecr.io/microservice-payments:latest
    build:
      context: .
      dockerfile: MicroserviceAPI.Payments/Dockerfile
    ports: 
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${PAYMENTS_DB_CONNECTION_STRING}

  microserviceapi.products:
    container_name: products-api
    image: testmicroservicesregistrydocker.azurecr.io/microservice-products:latest
    build:
      context: .
      dockerfile: MicroserviceAPI.Products/Dockerfile
    ports: 
      - "8082:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${PRODUCTS_DB_CONNECTION_STRING}
