apiVersion: v1
kind: Service
metadata:
  name: orders-service  # The service name used for internal communication
  namespace: default
spec:
  selector:
    app: orders  # Must match the labels in your Deployment YAML
  ports:
    - protocol: TCP
      port: 80       # The internal service port exposed within the cluster
      targetPort: 8080  # The port your container listens on
  type: ClusterIP  # Internal communication only
